name: ci-automatic

on:
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch:
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repositry
        uses: actions/checkout@v2

      - name: Get latest release of prymitive-karma-debian
        run: |
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/prymitive/karma/releases/latest > release.json

      - name: Extract version from release.json
        run: |
          extract=$(jq -r '.tag_name' <(cat release.json))
          echo "{ \"version\" : \"${extract}\" }" > version.json

      - name: Recommit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit updated version
          file_pattern: ./version.json
          commit_user_name: My GitHub Actions Bot
          commit_user_email: tim.and.trallnag+code@gmail.com

  build:
    needs: update
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repositry
        uses: actions/checkout@v2

      - name: Retrieve version
        run: |
          version=$(jq -r '.version' <(cat version.json))
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: trallnag/prymitive-karma-debian:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}

      - name: Update Dockerhub description
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPOSITORY: trallnag/prymitive-karma-debian
          README_FILEPATH: ./README.md 
