name: ci-manual

on:
  push:
    paths:
      - version.toml
  workflow_dispatch:
    
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repositry
        uses: actions/checkout@v2

      - name: Retrieve version
        run: |
          version=$(jq -r '.version' <(cat version.json))
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: trallnag/prymitive-karma-debian:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}

      - name: Update Dockerhub description
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPOSITORY: trallnag/prymitive-karma-debian
          README_FILEPATH: ./README.md 
